version: '2'

# Deploys a demo environment for the Cyclone Federation Provider
# complete with all tools + a samlidp.

services:

  keycloak:
    environment:
      - KCIMPORT
    volumes:
      - ./demo/kcexport.json:/opt/jboss/exports/kcexport.json

  samlbridge:
    volumes:
      - ./demo/samlbridge-idp-remote.php:/var/simplesamlphp/metadata/saml20-idp-remote.php

  samlidp:
    extends:
      file: docker-compose.yml
      service: samlbridge
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.backend=samlidp"
      - "traefik.frontend.rule=PathPrefix:/samlidp"
    environment:
      - FP_BASEURL
      - SAMLIDP_PASSWORD
      - SAMLIDP_SALT
      - SAMLIDP_CONTACTNAME
      - SAMLIDP_CONTACTEMAIL
    volumes:
      - ./components/samlbridge/samlbridge-cert:/var/simplesamlphp/cert
      - ./components/samlbridge/modules/cyclone:/var/simplesamlphp/modules/cyclone
      - ./demo/samlidp-config.php:/var/simplesamlphp/config/config.php
      - ./demo/samlidp-authsources.php:/var/simplesamlphp/config/authsources.php
      - ./demo/samlidp-idp-hosted.php:/var/simplesamlphp/metadata/saml20-idp-hosted.php
      - ./demo/samlidp-sp-remote.php:/var/simplesamlphp/metadata/saml20-sp-remote.php
      - ./demo/samlidp-000-default.conf:/etc/apache2/sites-available/000-default.conf
    expose:
      - "80"

